TRUTH = (
   "Kapan terakhir kali kamu berbohong?",
   "Kapan terakhir kali kamu menangis?",
   "Kapan terakhir kali kamu kentut?",
   "Apa ketakutan terbesarmu?",
   "Apa fantasi terhanehmu?",
    "Apa fantasi terbesarmu?",
   "Apa hal yang membuatmu senang, dan orangtuamu tidak mengetahuinya?",
   "Pernahkah kamu selingkuh?",
   "Apa hal terburuk yang pernah kamu lakukan?",
   "Apa rahasia yang tidak pernah kamu ceritakan kepada siapapun?",
   "Apakah kamu punya bakat terpendam?",
   "Siapa selebriti yang pertama kali bikin kamu naksir?",
   "Apa pendapatmu tentang perselingkuhan?",
   "Apa pengalaman intim terburuk yang pernah kamu alami?",
   "Apakah kamu pernah melanggar hukum?",
   "Apa hal paling memalukan yang pernah kamu lakukan? Kapan?",
   "Apa hal yang paling membuatmu merasa insecure?",
   "Kesalahan terburuk apa yang pernah kamu lakukan?",
   "Apa hal paling menjijikkan yang pernah kamu lakukan?",
   "Siapa orang yang paling ingin kamu cium di antara kita?",
   "Hal terburuk apa yang pernah dilakukan orang terhadapmu?",
   "Apa kebiasaan terburukmu?",
   "Hal terburuk apa yang pernah kamu katakan/lakukan terhadap orang lain?",
   "Apa penyesalan terburukmu?",
   "Kenapa kamu putus dengan mantan yang sebelumnya?",
   "Kalau kamu bisa jadi tidak terlihat, apa hal pertama yang akan kamu lakukan?",
   "Apa rahasia yang kamu sembunyikan dari orangtuamu?",
   "Siapa orang yang diam-diam kamu sukai?",
   "Siapa orang terakhir yang kamu kepoin di media sosial?",
   "Kalau ada jin yang memberikanmu tiga permohonan, apa yang kamu inginkan?",
   "Siapa orang di antara kita yang menurutmu bisa lolos dari kiamat zombie dan siapa yang akan mati duluan? Beri tahu alasannya!",
   "Apa tontonan favoritmu saat masih kecil?",
   "Siapa orang yang paling sering kamu chat?",
   "Apa kebohongan terbesar yang pernah kamu katakan kepada orangtuamu?",
   "Apa mimpi paling aneh yang pernah kamu alami?",
   "Ceritakan detail ciuman pertamamu…",
   "Kapan terakhir kali kamu ngompol?",
   "Menurutmu, hewan apa yang terlihat paling mirip denganmu?",
   "Di antara kita, siapa orang yang paling kamu suka dalam konteks romantis?",
   "Di antara kita, siapa orang yang menurutmu paling baik dan paling buruk sifatnya?",
   "Siapa mantan terindahmu?",
   "Siapa orang yang ingin kamu jadikan istri/suami?",
   "Apakah kamu pernah melakukan ghosting?",
   "Apa aib yang kamu sembunyikan dari kami?",
   "Berapa jumlah mantanmu?",


)

DARE = (
    "Ambil nomor secara acak dari kontakmu, telepon dia, dan bilang Aku mencintaimu",
    "Oncam Sekarang",
    "Coba Tahan Nafas Terus Oncam",
    "Ceritakan kepada semua orang kisah memalukan tentang dirimu",
    "Coba Cicip Garam",
    "Posting selfie tertua di ponsel Anda di Instagram Stories",
    "Ceritakan kisah paling menyedihkan yang kamu tahu",
    "Melolong seperti serigala sebanyak 2 kali",
    "Ngerap bebas selama 30 detik",
    "Telpon Random Orang dan bilang asu",
    "Kirim selfie terbaru Anda.",
    "Kirim selfie terjelekmu.",
    "Kirim tangkapan layar riwayat pencarian google Anda",
    "Kirim tangkapan layar galeri Anda.",
    "Kirim tangkapan layar kotak telegram Anda",
    "Katakan sesuatu yang sangat intim.",
    "Kirim tangkapan layar wa Anda",
    "Kirim tangkapan layar dm ig.",
    "Kirim cover lagu favoritmu. ",
    "Lakukan lelucon pada seseorang dan kirimkan buktinya.",
    "Akui gebetanmu saat ini. ❤️",
    "Ungkapkan siapa cinta sejatimu.",
    "Kirim tangkapan layar galeri Anda.",
    "Jadikan foto gebetanmu sebagai dpmu.",
    "Ngomong sunda 1 hari.",
    "Ngomong jawa 1 hari.",
    "pakai pp teman random dios 1 hari.",
    "pakai buat lirik 2 bait random.",
    "buat dark joke dan lontarkan ke teman random yang dios.",
    "buat joke dan lontarkan ke teman random yang dios.",
    "buat marah-marah ke orang random.",
     "bilang sayang ke orang yang dios.",
    
)
